name: rinha-backend-2024-q1
services:
    api1: &api
        image: wagfm/fastapi:0.1
        container_name: rinha-backend-2024-q1-api-1
        command: "uvicorn src.app:app --host 127.0.0.1 --port 8001 --workers 2"
        build:
            .
        environment: &api_env
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432
            POSTGRES_USER: rinha-backend
            POSTGRES_PASSWORD: rinha123
            POSTGRES_DATABASE: bank_db
        depends_on:
            postgres:
                condition: service_healthy
        restart: on-failure
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.42
                    memory: 150MB

    api2:
        <<: *api
        container_name: rinha-backend-2024-q1-api-2
        command: "uvicorn src.app:app --host 127.0.0.1 --port 8002 --workers 2"
        environment:
            <<: *api_env

    postgres:
        container_name: rinha-backend-2024-q1-postgres
        image: postgres:12.19-alpine
        environment:
            PGUSER: rinha-backend
            POSTGRES_USER: rinha-backend
            POSTGRES_PASSWORD: rinha123
            POSTGRES_DB: bank_db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U rinha-backend -d persons_db" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        volumes:
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.54
                    memory: 300MB

    nginx:
        container_name: rinha-backend-2024-q1-nginx
        image: nginx:1.27-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api1
            - api2
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.12
                    memory: 100MB
